### ISSUE TITLE
Missing doc on bluebrain.github.io

### ISSUE THREAD

**Issue by eile** [BlueBrain/Monsteer#10]
#9 did the release prep, but either the doc was not yet uploaded or it's broken for some reason. The space where Monsteer should be is empty on http://bluebrain.github.io/

**Comment by bilgili** [comment]
Interesting because http://bluebrain.github.io/Monsteer-0.3/ is there ? I will check again.

**Comment by eile** [comment]
The space where Monsteer should be is still empty on http://bluebrain.github.io/

**Comment by bilgili** [comment]
#11 fixed the problem. I thought I have seen it correctly. I think I checked BBPDocumentation.

**Comment by eile** [comment]
cool.
