### ISSUE TITLE
Online training with nest and troubles compiling monsteer

### ISSUE THREAD

**Issue by nash169** [BlueBrain/Monsteer#18]
Hi,
I'm trying to control the flight dynamic of a micro robot which uses flapping wings to generate lift end the three torques. I'm already using MUSIC to feed the neural network written in NEST. Relying on the suggestion of a NEST user I created two file C++ embedding MUSIC input and output ports. The first file takes the state coming from the robot. It transforms this continuous signal in a sequence of spikes (with a poisson generator) and transmits data to the neural network through an output port. The second file, through an input port, takes as input the spikes generated by the network and transforms them in a continuous signal (with a basic firing rate method) which will be used to control the robot. My big problem, right now, is the training/learning. Is it possible with this package changing weights during the simulation without stop it? Or, at least, is there a way to communicate to the network if it is performing well or not (transmitting the error between the actual and desired output or a reward)?

I installed the package but I can't see the music_proxy binary or the bbp python package. When I did cmake I got this messagge:
Configured Monsteer [0] with Boost Brion FlatBuffers Lunchbox MPI Qt5Widgets PythonInterp PythonLibs vmmlib zeq WITHOUT BBPTestData music

I've music installed in /usr/local instead of /usr (I installed monsteer in /usr). Is that the problem?

Thank you very much

**Comment by hernando** [comment]
The compilation problem is related to the migration from our MUSIC fork to use the official Github repository (we forked from the SVN repo long time ago). There were a couple of updates that weren't uploaded here. There's a PR that should get merged tomorrow.

After that's merged, you may probably still have problems due to your installation path. If that's the case, export MUSIC_ROOT=/usr/local before running CMake.

**Comment by nash169** [comment]
Thanks,
I just added export MUSIC_ROOT=/usr/local in the .bashrc but I got the same message after cmake. I'll wait for tomorrow. For the first problem I just answered to your email trying to explain better my problem and project.

Thank you again for helping me!

**Comment by eile** [comment]
Is this resolved now, or do you have further problems?

**Comment by nash169** [comment]
Thanks to hernando the problem is fixed. The cmake ends with MUSIC included in the configuration of Monster. I still get an error during the compilation of music_proxy.cpp but, as hernando told me, it's probably due to my version of MUSIC. I haven't been updating it for a while.
