### ISSUE TITLE
Compilation Error with MUSIC

### ISSUE THREAD

**Issue by MartyMcFlyHasNoFarmHiaHiaHo** [BlueBrain/Monsteer#8]
Machine specs:
32 bit
Ubuntu 14.04

When building Monsteer against the official MUSIC, the following issue pops up, this does not happen with the EPFL Music though but I would like to know whether the official Repro is working for others or if this a local problem. I am installing everything as non-admin, thus I use a CMake script for Monsteer and set the MUSIC_ROOT_DIR such that it can find MUSIC:

--------------------------------------------------------------------
"# Variables defined by this module:
"#
"#  MUSIC_FOUND              System has music libs/headers
"#  MUSIC_LIBRARIES          The music libraries
"#  MUSIC_INCLUDE_DIR        The location of music headers
"#  MUSIC_INCLUDE_DIRS        The location of music headers

find_path(MUSIC_ROOT_DIR
  NAMES include/music.hh
  HINTS $ENV{MUSIC_ROOT_DIR}
  )

find_library(MUSIC_LIBRARY
NAMES music libmusic
HINTS ${MUSIC_ROOT_DIR}/lib
)

find_path(MUSIC_INCLUDE_DIR
  NAMES music-c.h music.hh
  HINTS ${MUSIC_ROOT_DIR}/include
  )

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MUSIC DEFAULT_MSG
  MUSIC_LIBRARY
  MUSIC_INCLUDE_DIR
  )

set(MUSIC_INCLUDE_DIRS ${MUSIC_INCLUDE_DIR})
set(MUSIC_LIBRARIES ${MUSIC_LIBRARY})

mark_as_advanced(
  MUSIC_ROOT_DIR
  MUSIC_LIBRARY
  MUSIC_LIBRARY_DEBUG
  MUSIC_LIBRARY_RELEASE
  MUSIC_INCLUDE_DIR
  )
-----------------------------------------------------------------------

Here the Traceback:

Scanning dependencies of target music_spike_writer
[ 70%] Building CXX object Brion/brion/CMakeFiles/Brion.dir/morphology.cpp.o
[ 70%] Building CXX object apps/CMakeFiles/music_spike_writer.dir/music_spike_writer.cpp.o                                                                                                    
[ 72%] Building CXX object Brion/brion/CMakeFiles/Brion.dir/plugin/compartmentReportBinary.cpp.o                                                                                              
In file included from /disk/no_backup/schulze/builds_32/MUSIC/include/music/index_map.hh:22:0,
                 from /disk/no_backup/schulze/builds_32/MUSIC/include/music/data_map.hh:24,
                 from /disk/no_backup/schulze/builds_32/MUSIC/include/music/port.hh:26,
                 from /disk/no_backup/schulze/builds_32/MUSIC/include/music/setup.hh:27,
                 from /disk/no_backup/schulze/builds_32/MUSIC/include/music/runtime.hh:26,
                 from /disk/no_backup/schulze/builds_32/MUSIC/include/music.hh:21,
                 from /fzi/ids/schulze/Packages/Monsteer/apps/music_spike_writer.cpp:25:
/disk/no_backup/schulze/builds_32/MUSIC/include/music/interval.hh: In member function ‘void MUSIC::Interval::setBegin(int)’:
/disk/no_backup/schulze/builds_32/MUSIC/include/music/interval.hh:34:31: error: declaration of ‘begin’ shadows a member of 'this' [-Werror=shadow]
     void setBegin (int begin) { begin_ = begin; }
                               ^
/disk/no_backup/schulze/builds_32/MUSIC/include/music/interval.hh: In member function ‘void MUSIC::Interval::setEnd(int)’:
/disk/no_backup/schulze/builds_32/MUSIC/include/music/interval.hh:35:27: error: declaration of ‘end’ shadows a member of 'this' [-Werror=shadow]
     void setEnd (int end) { end_ = end; }
                           ^
In file included from /disk/no_backup/schulze/builds_32/MUSIC/include/music/port.hh:26:0,
                 from /disk/no_backup/schulze/builds_32/MUSIC/include/music/setup.hh:27,
                 from /disk/no_backup/schulze/builds_32/MUSIC/include/music/runtime.hh:26,
                 from /disk/no_backup/schulze/builds_32/MUSIC/include/music.hh:21,
                 from /fzi/ids/schulze/Packages/Monsteer/apps/music_spike_writer.cpp:25:
/disk/no_backup/schulze/builds_32/MUSIC/include/music/data_map.hh: In constructor ‘MUSIC::DataMap::DataMap(void*)’:
/disk/no_backup/schulze/builds_32/MUSIC/include/music/data_map.hh:43:26: error: declaration of ‘base’ shadows a member of 'this' [-Werror=shadow]
     DataMap (void* base) : base_ (base) { };
                          ^
In file included from /disk/no_backup/schulze/builds_32/MUSIC/include/music/port.hh:28:0,
                 from /disk/no_backup/schulze/builds_32/MUSIC/include/music/setup.hh:27,
                 from /disk/no_backup/schulze/builds_32/MUSIC/include/music/runtime.hh:26,
                 from /disk/no_backup/schulze/builds_32/MUSIC/include/music.hh:21,
                 from /fzi/ids/schulze/Packages/Monsteer/apps/music_spike_writer.cpp:25:
/disk/no_backup/schulze/builds_32/MUSIC/include/music/event.hh: At global scope:
/disk/no_backup/schulze/builds_32/MUSIC/include/music/event.hh:33:9: error: ‘class MUSIC::EventHandlerGlobalIndex’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
   class EventHandlerGlobalIndex {
         ^
/disk/no_backup/schulze/builds_32/MUSIC/include/music/event.hh:38:9: error: ‘class MUSIC::EventHandlerGlobalIndexDummy’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
   class EventHandlerGlobalIndexDummy : public EventHandlerGlobalIndex {
         ^
compilation terminated due to -fmax-errors=5.
cc1plus: all warnings being treated as errors
make[2]: *** [apps/CMakeFiles/music_spike_writer.dir/music_spik

**Comment by hernando** [comment]
Those errors occur because Monsteer adds several options to gcc to enable extra warnings and those options are also being applied to the MUSIC headers (those options are explicitly disabled in the compilation script from the EPFL clone). 

As a workaround, try replacing:

    set(MUSIC_INCLUDE_DIRS ${MUSIC_INCLUDE_DIR})

with

    set(MUSIC_INCLUDE_DIRS BEFORE SYSTEM ${MUSIC_INCLUDE_DIR})

in your find script. That tells gcc to not apply warning options to those headers.
The right place to add the SYSTEM flag is at the include_directories statement, but it's inside the Monsteer compilation scripts.

**Comment by MartyMcFlyHasNoFarmHiaHiaHo** [comment]
Thanks!

**Comment by hernando** [comment]
Could you please close the issue if it worked?
